# Generated by Django 5.0.3 on 2024-04-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_Name', models.CharField(max_length=50)),
                ('stu_Email', models.EmailField(max_length=254)),
                ('stu_Contact', models.IntegerField()),
                ('stu_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.departmentmodel')),
            ],
        ),
    ]
